# Default values for omar-upload.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1

appName: omar-upload

global:
  dockerRepository: nexus-docker-private-group.ossim.io
  imagePullSecret:
    registry: null
    username: null
    password: null
  hostname: omar-dev.ossim.io

  createIngress: true
  useTls: false
  useTLSClientAuth: false
  sslCertSecretName: null
  authSslCertSecretName: null

  createImagePullSecret: true
  useImagePullSecret: true
  
  createHpa: true
  createPVs: true

  useSpringConfigServer: false

  volumes:
    ossimData:
      type: nfs
      nfsServer: 10.70.40.254
      nfsMountPoint: /omar-3pa-dev-nfs/buzz-test
      accessModes:
        - ReadWriteMany
      size: 500gi
      mountPath: /buzz-test

volumes:
  ossimData: null

# These variables can be overridden because of the use of the 'pluck' function:
# - createIngress
# - useTls
# - useTlsClientAuth
# - createImagePullSecret
# - createHpa
# - createPVs
# - useSpringConfigServer

resources:
  limits:
    cpu: 1500m
    memory: 1000Mi
  requests:
    cpu: 20m
    memory: 500Mi
    
image:
  name: omar-upload
  tag: dev
  pullPolicy: Always

ingressPath: /omar-upload
internalPort: 8080
externalPort: 8080

livenessProbe:
  failureThreshold: 5
  initialDelaySeconds: 30
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 3


readinessProbe:
  failureThreshold: 15
  initialDelaySeconds: 30
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 3

terminationGracePeriodSeconds: 30

envVars:
  SPRING_CLOUD_CONFIG_LABEL: master
  JAVA_OPTS: "-server -Xms256m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1 -XX:+CMSClassUnloadingEnabled -XX:+UseGCOverheadLimit -Djava.awt.headless=true -XshowSettings:vm -Djava.security.egd=file:/dev/./urandom"
