# Default values for omar-upload.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1

appName: omar-upload

global:
  omarDb:
    name: o2_omar_db
    host: omar-3pa-dev.cfussmnw2zzg.us-east-1.rds.amazonaws.com
    user: postgres
    password: "szSr.7TtLN3P9xN5y_Tyis7lHE8mAN"
    port: 5432
  dockerRepository: nexus-docker-public-hosted.ossim.io
  imagePullSecret:
    registry: nexus-3pa-dev-docker-proxy.ossim.io
    username: radiantcibot
    password: 498uKJp56uhG1bvC
  hostname: omar-3pa-dev.ossim.io

  createIngress: true
  useTls: false
  useTLSClientAuth: false
  sslCertSecretName: ssl-certs
  authSslCertSecretName: null

  createImagePullSecret: true
  useImagePullSecret: true
  
  createHpa: true
  createPVs: true

  useSpringConfigServer: false

  volumes:
    upload-data:
      type: nfs
      nfsServer: "10.20.150.239"
      nfsMountPoint: /omar-3pa-dev-nfs/3pa-blacksky
      accessModes:
        - ReadWriteMany
      size: 50Gi
      mountPath: /3pa-blacksky

volumeNames:
  - upload-data

baseUrl: https://omar-3pa-dev.ossim.io

# These variables can be overridden because of the use of the 'pluck' function:
# - createIngress
# - useTls
# - useTlsClientAuth
# - createImagePullSecret
# - createHpa
# - createPVs
# - useSpringConfigServer

resources:
  limits:
    cpu: 1500m
    memory: 1000Mi
  requests:
    cpu: 20m
    memory: 500Mi
    
image:
  name: omar-upload
  tag: 1.0.6
  pullPolicy: Always

ingressPath: /omar-upload
internalPort: 8080
externalPort: 8080

livenessProbe:
  failureThreshold: 5
  initialDelaySeconds: 30
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 3


readinessProbe:
  failureThreshold: 15
  initialDelaySeconds: 30
  periodSeconds: 15
  successThreshold: 1
  timeoutSeconds: 3

terminationGracePeriodSeconds: 30

envVars:
  UPLOAD_PATH: /3pa-blacksky/upload-test
  UPLOAD_URL: https://omar-3pa-dev.ossim.io/omar-stager/dataManager/addRaster?filename=
  UPLOAD_SUFFIX: "&background=true&buildThumbnails=true&buildOverviews=true&buildHistograms=true&buildHistogramsWithR0=true&useFastHistogramStaging=false&overviewType=ossim_tiff_box&overviewCompressionType=NONE&thumbnailSize=512&thumbnailType=jpeg&thumbnailStretchType=auto-minmax"
  SPRING_CLOUD_CONFIG_LABEL: master
  JAVA_OPTS: "-server -Xms256m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1 -XX:+CMSClassUnloadingEnabled -XX:+UseGCOverheadLimit -Djava.awt.headless=true -XshowSettings:vm -Djava.security.egd=file:/dev/./urandom"

upload:
  imageUploadPath: /3pa-blacksky/upload-test
  baseUrl: https://omar-3pa-dev.ossim.io/omar-stager/dataManager/addRaster?filename=
  suffix: "&background=true&buildThumbnails=true&buildOverviews=true&buildHistograms=true&buildHistogramsWithR0=true&useFastHistogramStaging=false&overviewType=ossim_tiff_box&overviewCompressionType=NONE&thumbnailSize=512&thumbnailType=jpeg&thumbnailStretchType=auto-minmax"

configmaps:
  omar-upload:
    file: application.yaml
