---
swagger:
  schemes:
    - HTTPS
    - HTTP

omar:
  upload:
    maxFiles: 10
    destinationPath: ./

serverDomain: localhost
serverName: ${serverDomain}
serverProtocol: http

omarWfsUrl: ${serverProtocol}://${serverName}/omar-wfs/wfs/
omarUiUrl: ${serverProtocol}://${serverName}/omar-ui/omar#/map

baseWfsQuery: "getFeature?service=WFS&version=1.1.0&request=GetFeature&typeName=omar:raster_entry&resultType=results&outputFormat=JSON&maxFeatures=1"